

INSERT INTO VEICULOS(PLACA,MARCA,MODELO,ANO,PRECO,SIGLA,ESTADO,LOJA) 
VALUES('ASF-1232','HONDA','SEDAN',2013,22000,'GO','GOIAS','FUMO');


INSERT INTO VEICULOS(PLACA,MARCA,MODELO,ANO,PRECO,SIGLA,ESTADO,LOJA) 
VALUES('OSO-4021','CORSA','VECTRA',2013,10000,'MG','MATOGROSSO','TURBO');

INSERT INTO VEICULOS(PLACA,MARCA,MODELO,ANO,PRECO,SIGLA,ESTADO,LOJA) 
VALUES('GIU-1316','TRISTE','SEDAN',2014,404404,'SP','SAOPAULO','FEREGUETTI');

INSERT INTO VEICULOS(PLACA,MARCA,MODELO,ANO,PRECO,SIGLA,ESTADO,LOJA) 
VALUES('PLS-1000','ESKO','VECTRA',2014,12312,'SP','SAOPAULO','COTN');


INSERT INTO VEICULOS(PLACA,MARCA,MODELO,ANO,PRECO,SIGLA,ESTADO,LOJA) 
VALUES('PAO-1202','XAMBRA','SEDAN',2014,30212,'SP','SAOPAULO','COTN');
SELECT * FROM VEICULOS;
/*
a.
*/
SELECT ESTADO,SIGLA,MARCA FROM VEICULOS;

/*
b.
*/
SELECT MARCA,MODELO,ANO,PLACA,LOJA FROM VEICULOS;

/*
c.
*/

SELECT COUNT(DISTINCT MARCA)AS "NUMERO DE VEICULOS",COUNT(DISTINCT MODELO)AS "NUMERO DE MODELOS" FROM VEICULOS;

SELECT COUNT(DISTINCT MARCA) AS "NUMERO DE VEICULOS SEDAN"
FROM VEICULOS
WHERE MODELO= 'SEDAN';
SELECT COUNT(DISTINCT MARCA) AS "NUMERO DE VEICULOS VECTRA"
FROM VEICULOS
WHERE MODELO= 'VECTRA';

SELECT ANO,MAX(PRECO)AS "MAIOR PREÇO",MIN(PRECO)AS "MENOR PREÇO"
FROM VEICULOS
GROUP BY ANO;

SELECT * FROM VEICULOS;


CREATE TABLE USUARIO(ID VARCHAR(50),LOGIN VARCHAR(50),SENHA VARCHAR(50));
INSERT INTO USUARIO(LOGIN,SENHA) VALUES("trem","123");

SELECT * FROM VEICULOS;

SELECT * FROM USUARIO;

UPDATE VEICULOS SET PLACA='CCC',MARCA='FODASE',MODELO='QUENGA',ANO='1111',PRECO='14212',SIGLA='CHAMA',ESTADO='CAGUEI',LOJA='FOOODASE'
WHERE PLACA='ASD';